package com.luisansal.jetpack.features.main

enum class FeaturesEnum(val code: Int, val title: String) {
    ROOM_USER_MANAGER(0,"ROOM_DATABASE"),
    MAPS(0,"MAPS"),
    MULTIMEDIA(0,"MULTIMEDIA"),
    CHAT(0,"CHAT"),
    DESIGN(0,"DESIGN"),
    ONBOARDING(0,"ONBOARDING"),
    BROADCAST_RECEIVER(0,"BROADCAST_RECEIVER"),
    VIEW_PAGER(0,"VIEW_PAGER"),
    VIEW_BINDING_COUNTDOWN(0,"VIEW_BINDING_COUNTDOWN"),
    WORK_MANAGER(0,"WORK_MANAGER"),
    ALARM_MANAGER(0,"ALARM_MANAGER"),
    SALES_MANAGER(0,"SALES_MANAGER"),
    MENU(0,"MENU"),
}