package com.luisansal.jetpack.domain.analytics

enum class TagAnalytics {
    //PANTALLAS
    RUTA_DESARROLLO_DASHBOARD,
    MI_RUTA_DESARROLLO_LISTADO,
    PERFIL_ACOMPANIAMIENTO,
    PERFIL_DATOS,
    MI_RUTA_MAPA,
    PLANIFICAR_VISITA,
    RE_PLANIFICAR_VISITA,
    ELIMINA_TU_CALENDARIO,
    INDICADOR_VENTA_NETA,
    INDICADOR_PEDIDOS,
    INDICADOR_ACTIVIDAD,
    INDICADORES_CAPITALIZACION,
    INDICADORES_COBRANZA,
    INIDCADORES_PEDIDOS_VTA,
    INDICADORES_CICLO_NUEVAS,
    INDICADORES_UNETE,
    INDICADORES_PEG,
    INDICADORES_PEGS,

    //EVENTOS
    EVENTO_CREAR_USUARIO,
    EVENTO_MOSTRAR_USUARIOS,
    EVENTO_HOME_INDICADORES_MI_RUTA,
    EVENTO_HOME_MENU_INFERIOR_MI_RUTA,
    EVENTO_MENU_MI_RUTA_ELIMINAR,
    EVENTO_MENU_MI_RUTA_REPLANIFICAR,
    EVENTO_MENU_MI_RUTA_VISITA,
    EVENTO_MENU_MI_RUTA_MAPA,
    EVENTO_MENU_MI_RUTA_WHATSAPP,
    EVENTO_MENU_MI_RUTA_LLAMAR,
    EVENTO_MENU_MI_RUTA_SMS,
    EVENTO_MENU_MODAL_ELIMINAR_PLANIFICADA,
    EVENTO_MENU_MODAL_ELIMINAR_PLANIFICADA_ACEPTAR,
    EVENTO_PERFIL_DATOS,
    EVENTO_FINALIZAR_VISITA,
    EVENTO_COMPARTIR_VIDEO,
    EVENTO_CREAR_ACUERDO,
    EVENTO_RECONOCER_COMPORTAMIENTO,
    EVENTO_RECONOCER_HABILIDADES,
    EVENTO_SWITCH_LISTA,
    EVENTO_SWITCH_MAPA,
    EVENTO_VER_MI_RUTA_MAPA,
    EVENTO_MARCAR_MAPA,
    EVENTO_MI_RUTA_TAB_PLANIFICADAS,
    EVENTO_MI_RUTA_TAB_NO_PLANIFICADAS,
    EVENTO_MI_RUTA_TAB_BUSQUEDA,
    EVENTO_SWITCH_ACTIVAR_MAPA,
    EVENTO_PLANIFICAR_VISITA,
    EVENTO_PLANIFICAR_ACOMPANIAMIENTO_VISITA,
    EVENTO_PLANIFICAR_ACEPTAR_VISITA,
    EVENTO_RE_PLANIFICAR_VISITA,
    EVENTO_RE_PLANIFICAR_ACOMPANIAMIENTO_VISITA,
    EVENTO_RE_PLANIFICAR_ACEPTAR_VISITA,//EVENTO_PLANIFICAR_ACEPTAR_VISITA
    EVENTO_REGISTRAR_VISITA,

    EVENTO_COBRANZA,
    EVENTO_CONTACTO,
    EVENTO_ESTADO_CUENTA,
    EVENTO_MIS_ANOTACIONES,
    EVENTO_METAS_CONSULTORA,

    EVENTO_VER_MAS,

    EVENTO_VER_MAS_CLICK,

    EVENTO_MATERIAL_DE_DESARROLLO,

    EVENTO_MATERIAL_DE_DESARROLLO_VISUALIZAR_Y_DESACARGAR;
}